name: test

on:
  push:
    branches-ignore:
      - 'release-please-**'
      - 'hyprshell-release'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-nix:
    name: Run Nix Flake Check
    runs-on: "ubuntu-latest"
    container:
      image: ghcr.io/h3rmt/actions-image:latest@sha256:6fd397a957de68ed34d77d4a37e2cffb1e15965c0fdbc84d9d69bf9fcabbd688
      options: --privileged
    steps:
      - run: rustup default stable
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: cachix/cachix-action@0fc020193b5a1fa3ac4575aa3a7d3aa6a35435ad # v16
        with:
          name: hyprshell-dev
          extraPullNames: hyprland
          pushFilter: "hyprshell-(nextest|clippy|fmt|check-all-feature-combinations|check-nix-configs).*"
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN_DEV }}
      - name: Run Nix Flake Build deps
        run: nix build '.#checks.x86_64-linux.hyprshell-build-deps' -L
      - name: Run Nix Flake Check build
        run: nix build '.#checks.x86_64-linux.hyprshell-config-check' -L
      - name: Run Nix Flake Check clippy
        run: nix build '.#checks.x86_64-linux.hyprshell-clippy' -L
      - name: Run Nix Flake Check fmt
        run: nix build '.#checks.x86_64-linux.hyprshell-fmt' -L
      - name: Run Nix Flake Check test
        run: nix build '.#checks.x86_64-linux.hyprshell-test' -L
      - name: Run Nix Flake Check check-nix-configs
        run: nix build '.#checks.x86_64-linux.hyprshell-check-nix-configs' -L
      - name: Run Nix Flake Check check-all-feature-combinations
        run: nix build '.#checks.x86_64-linux.hyprshell-check-all-feature-combinations' -L

  check:
    name: Run build tests
    runs-on: "ubuntu-latest"
    container:
      image: ghcr.io/h3rmt/actions-image:latest@sha256:6fd397a957de68ed34d77d4a37e2cffb1e15965c0fdbc84d9d69bf9fcabbd688
      options: --privileged
    if: github.ref == 'refs/heads/hyprshell'
    steps:
      - run: rustup default stable
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: hyprshell
          cache-on-failure: true
      - name: Build binary for x86_64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell.sh
          ./scripts/ci/build-x86.sh
      - name: Build binary for aarch64-unknown-linux-gnu
        run: |
          ./scripts/ci/install-gtk4-layer-shell-aarch64.sh
          ./scripts/ci/build-aarch64.sh

